const state={csrf:'',plans:[],settings:[],me:null};
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function showAlert(message,success=false){const el=$('alert');el.hidden=!message;el.textContent=message||'';el.className='alert'+(success?' success':'');if(message)setTimeout(()=>{el.hidden=true},4500)}
async function req(path,opt={}){const headers={'Accept':'application/json',...(opt.headers||{})};if(opt.body&&typeof opt.body!=='string'){headers['Content-Type']='application/json';opt.body=JSON.stringify(opt.body)}if(opt.method&&opt.method!=='GET'){headers['X-CSRF-Token']=state.csrf}const r=await fetch(path,{cache:'no-store',...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed.');return d}
function status(v){return `<span class="status-pill status-${esc(v)}">${esc(v)}</span>`}
function fmtDate(v){if(!v)return '—';try{return new Date(v).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}catch{return v}}
function openModal(title,body,kicker='ADMIN'){ $('modal-kicker').textContent=kicker;$('modal-title').textContent=title;$('modal-body').innerHTML=body;$('modal').hidden=false }
function closeModal(){$('modal').hidden=true;$('modal-body').innerHTML=''}
$('modal-close').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()});
async function bootstrap(){try{const me=await req('/v1/auth/me');if(!me.authenticated||me.user?.role!=='admin'){location.href='/auth?mode=login';return}state.me=me.user;$('admin-email').textContent=me.user.email;state.csrf=(await req('/v1/admin/csrf')).csrf_token;await loadOverview()}catch(e){showAlert(e.message)}}
function activateSection(name){document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===`section-${name}`));document.querySelectorAll('#side-nav button').forEach(x=>x.classList.toggle('active',x.dataset.section===name));$('page-title').textContent=name.replace(/(^|_)(\w)/g,(_,a,b)=>' '+b.toUpperCase()).trim();
  if(name==='users')loadUsers();if(name==='keys')loadKeys();if(name==='plans')loadPlans();if(name==='subscriptions')loadSubscriptions();if(name==='payments')loadBilling();if(name==='coupons')loadCoupons();if(name==='grants')loadGrants();if(name==='ads')loadAds();if(name==='embeds')loadEmbeds();if(name==='settings')loadSettings();if(name==='audit')loadAudit();}
document.querySelectorAll('#side-nav button').forEach(b=>b.onclick=()=>activateSection(b.dataset.section));document.querySelectorAll('[data-section]').forEach(b=>{if(!b.closest('#side-nav'))b.onclick=()=>activateSection(b.dataset.section)});
async function loadOverview(){const d=await req('/v1/admin/overview');const bb=d.billing||{};const cards=[['Users',d.users,d.verified_users+' verified'],['Active subscriptions',d.active_subscriptions,''],['API keys',d.active_api_keys,'active'],['Settled USDT',bb.settled_revenue_usdt||'$'+Number(d.confirmed_revenue_usdt||0).toFixed(2),'blockchain billing'],['API scans this month',d.api_scans_reserved_this_month,'reserved'],['Active batches',d.active_batches,'queued or running'],['Invoices awaiting payment',bb.awaiting_payment||0,'crypto billing'],['Unmatched transfers',bb.unmatched_events||0,'manual review if needed']];$('stats-grid').innerHTML=cards.map(c=>`<div class="stat"><div class="label">${esc(c[0])}</div><div class="value">${esc(c[1])}</div><div class="sub">${esc(c[2])}</div></div>`).join('');renderQuickSettings(d.settings);state.plans=(await req('/v1/admin/plans')).plans;renderOverviewPlans();}
function renderQuickSettings(settings){$('quick-settings').innerHTML=settings.map(s=>`<div class="switch-row"><div><strong>${esc(s.key)}</strong><small>${esc(s.description||'')}</small></div><button class="toggle ${s.value==='true'?'on':''}" data-setting="${esc(s.key)}" data-value="${esc(s.value)}"></button></div>`).join('');document.querySelectorAll('#quick-settings .toggle').forEach(b=>b.onclick=()=>toggleSetting(b.dataset.setting,b.dataset.value!=='true'))}
function renderOverviewPlans(){$('overview-plans').innerHTML=state.plans.map(p=>`<div class="mini-plan"><div class="row"><b>${esc(p.name)}</b><span class="muted">$${p.price_usdt}/mo</span></div><div class="row"><small>${p.monthly_scan_limit.toLocaleString()} scans</small><small>${p.batch_limit.toLocaleString()} / batch · ${p.requests_per_second} RPS</small></div></div>`).join('')}
async function toggleSetting(key,value){try{await req(`/v1/admin/settings/${encodeURIComponent(key)}`,{method:'POST',body:{value}});showAlert('Setting updated.',true);await loadOverview()}catch(e){showAlert(e.message)}}
async function loadUsers(){const d=await req(`/v1/admin/users?search=${encodeURIComponent($('user-search').value)}&status=${encodeURIComponent($('user-status').value)}`);$('users-table').innerHTML=d.data.map(u=>`<tr><td><strong>${esc(u.email)}</strong><div class="muted">${esc(u.id)}</div></td><td>${status(u.status)} ${u.email_verified?'':'<span class="muted">unverified</span>'}</td><td>${esc(u.subscription?.plan_id||'—')}</td><td>${u.active_api_keys}</td><td>${fmtDate(u.created_at)}</td><td><div class="row-actions"><button class="small-btn icon-action" data-user="${u.id}" data-action="detail">View</button><button class="small-btn icon-action" data-user="${u.id}" data-action="status">Status</button></div></td></tr>`).join('')||`<tr><td colspan="6" class="muted">No users found.</td></tr>`;bindUserActions()}
$('load-users').onclick=loadUsers;$('user-search').onkeydown=e=>{if(e.key==='Enter')loadUsers()};function bindUserActions(){document.querySelectorAll('[data-user]').forEach(b=>b.onclick=async()=>{const id=b.dataset.user;if(b.dataset.action==='detail'){const d=await req(`/v1/admin/users/${id}/detail`);openUserDetail(d)}else openUserAction(id)})}
function openUserDetail(d){openModal('User details',`<div class="detail-grid"><div class="detail-box"><small>Email</small><strong>${esc(d.user.email)}</strong></div><div class="detail-box"><small>Status</small><strong>${status(d.user.status)}</strong></div><div class="detail-box"><small>Role</small><strong>${esc(d.user.role)}</strong></div><div class="detail-box"><small>Plan</small><strong>${esc(d.subscription?.plan_id||'—')}</strong></div></div><h4>API keys</h4>${d.api_keys.map(k=>`<div class="mini-plan"><b>${esc(k.name)}</b> · ${status(k.status)}<div class="muted code">${esc(k.prefix)}••••${esc(k.last4)}</div></div>`).join('')||'<p class="muted">No keys.</p>'}`)}
async function openUserAction(id){try{const d=await req(`/v1/admin/users/${id}/detail`);openModal('Manage user',`<div class="modal-form"><label>Account status<select id="m-user-status"><option>active</option><option>suspended</option><option>deleted</option></select></label><label>Role<select id="m-user-role"><option>user</option><option>admin</option></select></label><label>Plan<select id="m-user-plan"></select></label><label>Subscription status<select id="m-user-sub"><option>active</option><option>trialing</option><option>past_due</option><option>canceled</option><option>expired</option></select></label><label>Ends at <input id="m-user-end" placeholder="ISO datetime optional"></label><div class="modal-actions"><button class="ghost" onclick="closeModal()">Cancel</button><button class="primary" id="save-user">Save changes</button></div></div>`);$('m-user-plan').innerHTML=state.plans.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('m-user-status').value=d.user.status;$('m-user-role').value=d.user.role;if(d.subscription){$('m-user-plan').value=d.subscription.plan_id;$('m-user-sub').value=d.subscription.status;$('m-user-end').value=d.subscription.ends_at||''} $('save-user').onclick=async()=>{try{await req(`/v1/admin/users/${id}/status`,{method:'POST',body:{status:$('m-user-status').value}});await req(`/v1/admin/users/${id}/role`,{method:'POST',body:{role:$('m-user-role').value}});if(d.subscription||$('m-user-sub').value!=='expired'){await req(`/v1/admin/users/${id}/subscription`,{method:'POST',body:{plan_id:$('m-user-plan').value,status:$('m-user-sub').value,ends_at:$('m-user-end').value||null}})}closeModal();showAlert('User updated.',true);loadUsers()}catch(e){showAlert(e.message)}}}catch(e){showAlert(e.message)}}
async function loadKeys(){const d=await req(`/v1/admin/api-keys?search=${encodeURIComponent($('key-search').value)}&status=${encodeURIComponent($('key-status').value)}`);$('keys-table').innerHTML=d.data.map(k=>`<tr><td><b>${esc(k.name)}</b><div class="code">${esc(k.prefix)}••••${esc(k.last4)}</div></td><td><strong>${esc(k.user.email)}</strong><div class="muted">${esc(k.user.id)}</div></td><td>${esc(k.user.plan_id||'—')}</td><td>${status(k.status)}</td><td>${fmtDate(k.last_used_at)}</td><td><div class="row-actions">${k.status==='active'?`<button class="small-btn icon-action" onclick="setKey('${k.id}','disabled')">Disable</button><button class="small-btn icon-action danger-btn" onclick="setKey('${k.id}','revoked')">Revoke</button>`:k.status==='disabled'?`<button class="small-btn icon-action" onclick="setKey('${k.id}','active')">Enable</button><button class="small-btn icon-action danger-btn" onclick="setKey('${k.id}','revoked')">Revoke</button>`:'—'}</div></td></tr>`).join('')||`<tr><td colspan="6" class="muted">No API keys found.</td></tr>`}
$('load-keys').onclick=loadKeys;window.setKey=async(id,state)=>{if(!confirm(`${state==='revoked'?'Permanently revoke':'Set'} this key to ${state}?`))return;try{await req(`/v1/admin/api-keys/${id}`,{method:'POST',body:{state}});showAlert('API key updated.',true);loadKeys()}catch(e){showAlert(e.message)}};
async function loadPlans(){state.plans=(await req('/v1/admin/plans')).plans;$('plans-grid').innerHTML=state.plans.map(p=>`<div class="plan-card"><div class="panel-head"><div><span class="eyebrow">API PLAN</span><h3>${esc(p.name)}</h3></div><span>${p.active?status('active'):status('disabled')}</span></div><div class="plan-price">$${Number(p.price_usdt).toLocaleString()} <small>USDT / month</small></div><div class="detail-grid"><div class="detail-box"><small>Monthly scans</small><strong>${p.monthly_scan_limit.toLocaleString()}</strong></div><div class="detail-box"><small>Batch limit</small><strong>${p.batch_limit.toLocaleString()}</strong></div><div class="detail-box"><small>RPS</small><strong>${p.requests_per_second}</strong></div><div class="detail-box"><small>Concurrency</small><strong>${p.concurrency}</strong></div><div class="detail-box"><small>Active batches</small><strong>${p.max_active_batches}</strong></div></div><div class="modal-actions"><button class="small-btn" onclick="editPlan('${p.id}')">Edit limits & price</button></div></div>`).join('')}
window.editPlan=id=>{const p=state.plans.find(x=>x.id===id);openModal(`Edit ${p.name}`,`<div class="modal-form"><label>Monthly price (USDT)<input id="p-price" type="number" step="0.01" value="${p.price_usdt}"></label><label>Monthly scans<input id="p-monthly" type="number" value="${p.monthly_scan_limit}"></label><label>Max batch<input id="p-batch" type="number" value="${p.batch_limit}"></label><label>Requests / second<input id="p-rps" type="number" value="${p.requests_per_second}"></label><label>Worker concurrency<input id="p-conc" type="number" value="${p.concurrency}"></label><label>Max active batches<input id="p-active" type="number" value="${p.max_active_batches}"></label><label>Plan active<select id="p-enabled"><option value="true" ${p.active?'selected':''}>Yes</option><option value="false" ${!p.active?'selected':''}>No</option></select></label><div class="modal-actions"><button class="primary" id="save-plan">Save plan</button></div></div>`);$('save-plan').onclick=async()=>{try{await req(`/v1/admin/plans/${id}`,{method:'POST',body:{price_usdt:+$('p-price').value,monthly_scan_limit:+$('p-monthly').value,batch_limit:+$('p-batch').value,requests_per_second:+$('p-rps').value,concurrency:+$('p-conc').value,max_active_batches:+$('p-active').value,active:$('p-enabled').value==='true'}});closeModal();showAlert('Plan updated.',true);loadPlans()}catch(e){showAlert(e.message)}}}
async function loadSubscriptions(){state.plans=(await req('/v1/admin/plans')).plans;$('sub-plan').innerHTML=state.plans.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');const d=await req('/v1/admin/users?limit=100');$('subs-table').innerHTML=d.data.filter(u=>u.subscription).map(u=>`<tr><td><strong>${esc(u.email)}</strong><div class="muted">${esc(u.id)}</div></td><td>${esc(u.subscription.plan_id)}</td><td>${status(u.subscription.status)}</td><td>${fmtDate(u.subscription.ends_at)}</td></tr>`).join('')||`<tr><td colspan="4" class="muted">No subscriptions.</td></tr>`}
$('save-sub').onclick=async()=>{try{await req(`/v1/admin/users/${encodeURIComponent($('sub-user-id').value)}/subscription`,{method:'POST',body:{plan_id:$('sub-plan').value,status:$('sub-status').value,ends_at:$('sub-end').value||null}});showAlert('Subscription saved.',true);loadSubscriptions()}catch(e){showAlert(e.message)}}
async function loadBilling(){
  try{
    const [overview, invoices, unmatched] = await Promise.all([
      req('/v1/admin/billing/overview'),
      req(`/v1/admin/billing/invoices?status=${encodeURIComponent($('billing-status').value)}&search=${encodeURIComponent($('billing-search').value)}&limit=100`),
      req('/v1/admin/billing/unmatched?limit=50')
    ]);
    const b=overview;
    const runtime=b.runtime||{};
    const receiver=b.receiver_address||'—';
    $('billing-health').innerHTML=`<div class="billing-health-grid">
      <div><span class="eyebrow">BILLING RUNTIME</span><strong>${runtime.monitor_running?'Monitor running':'Monitor not running'}</strong><small>${runtime.configured?'Production configuration valid':'Configuration incomplete'}</small></div>
      <div><span>Network</span><strong>${esc(b.network)}</strong><small>Chain ${esc(b.chain_id)} · ${esc(b.token)}</small></div>
      <div><span>Receiver</span><strong class="code">${esc(receiver)}</strong><small>${b.receiver_valid?'Address valid':'Address not configured'}</small></div>
      <div><span>USDT contract</span><strong class="code">${esc(b.token_contract)}</strong><small>${b.token_contract==='0xdac17f958d2ee523a2206206994597c13d831ec7'?'Approved Ethereum USDT':'Unexpected token contract'}</small></div>
      <div><span>Scanner cursor</span><strong>${b.scanner_next_block??'—'}</strong><small>${fmtDate(b.scanner_updated_at)}</small></div>
    </div>`;
    const cards=[
      ['Invoices',b.invoices_total,'' ],['Awaiting payment',b.awaiting_payment,'open'],['Confirming',b.confirming,'finality pending'],['Settled',b.paid,b.settled_revenue_usdt+' USDT'],['Unmatched events',b.unmatched_events,'never auto-activated'],['Rejected events',b.rejected_events,'review']
    ];
    $('billing-stats').innerHTML=cards.map(c=>`<div class="stat"><div class="label">${esc(c[0])}</div><div class="value">${esc(c[1])}</div><div class="sub">${esc(c[2])}</div></div>`).join('');
    $('billing-invoice-count').textContent=`${invoices.pagination.total} invoice${invoices.pagination.total===1?'':'s'}`;
    $('billing-invoices-table').innerHTML=invoices.data.map(inv=>{
      const pe=inv.payment_event;
      const tx=pe?.tx_hash?`${esc(pe.tx_hash.slice(0,10))}…${esc(pe.tx_hash.slice(-8))}`:'—';
      const payment=pe?`${tx}<div class="muted">block ${pe.block_number??'—'} · ${pe.confirmations??0} final</div>`:'—';
      const expiry=inv.paid_at?`Paid ${fmtDate(inv.paid_at)}`:`Expires ${fmtDate(inv.expires_at)}`;
      return `<tr><td><strong>${esc(inv.email)}</strong><div class="muted">${esc(inv.id)}</div></td><td><strong>${esc(inv.plan_name)}</strong><div>${esc(inv.payment_amount_usdt)} USDT</div><div class="muted">base ${esc(inv.base_price_usdt)}</div></td><td>${status(inv.status)}${inv.expected_payer_address?`<div class="muted">payer locked</div>`:''}</td><td>${payment}</td><td>${expiry}</td><td><button class="small-btn icon-action" onclick="viewBillingInvoice('${esc(inv.id)}')">View</button></td></tr>`;
    }).join('')||`<tr><td colspan="6" class="muted">No invoices match the current filter.</td></tr>`;
    $('billing-unmatched-count').textContent=`${unmatched.pagination.total} event${unmatched.pagination.total===1?'':'s'}`;
    $('billing-unmatched-table').innerHTML=unmatched.data.map(e=>`<tr><td>${fmtDate(e.first_seen_at)}</td><td><strong>${esc(e.amount_usdt)} USDT</strong></td><td><span class="code">${esc(e.from_address.slice(0,10))}…${esc(e.from_address.slice(-8))}</span></td><td><span class="code">${esc(e.tx_hash.slice(0,12))}…${esc(e.tx_hash.slice(-8))}</span></td><td>${esc(e.block_number)}</td><td>${status(e.status)}${e.rejection_code?`<div class="muted">${esc(e.rejection_code)}</div>`:''}</td></tr>`).join('')||`<tr><td colspan="6" class="muted">No unmatched blockchain events.</td></tr>`;
  }catch(e){showAlert(e.message)}
}
window.viewBillingInvoice=async id=>{try{const d=await req(`/v1/admin/billing/invoices/${encodeURIComponent(id)}`);const i=d.invoice;const events=d.events||[];const eventRows=events.map(e=>`<div class="billing-event-detail"><div><b>${esc(e.amount_usdt)} USDT</b> · ${status(e.status)}</div><div class="muted code">${esc(e.tx_hash)}</div><div class="detail-grid"><div class="detail-box"><small>From</small><strong class="code">${esc(e.from_address)}</strong></div><div class="detail-box"><small>Block</small><strong>${esc(e.block_number)} · ${esc(e.confirmations)} final</strong></div><div class="detail-box"><small>Receipt</small><strong>${e.receipt_status===1?'Success':'Failed'}</strong></div><div class="detail-box"><small>Rejection</small><strong>${esc(e.rejection_code||'—')}</strong></div></div></div>`).join('')||'<p class="muted">No payment events linked yet.</p>';const settlement=d.settlement?`<div class="detail-grid"><div class="detail-box"><small>Settlement</small><strong class="code">${esc(d.settlement.id)}</strong></div><div class="detail-box"><small>Subscription</small><strong class="code">${esc(d.settlement.subscription_id)}</strong></div><div class="detail-box"><small>Status</small><strong>${status(d.settlement.status)}</strong></div><div class="detail-box"><small>Ends</small><strong>${fmtDate(d.settlement.ends_at)}</strong></div></div>`:'<p class="muted">No settlement recorded.</p>';openModal('Crypto invoice',`<div class="detail-grid"><div class="detail-box"><small>Invoice</small><strong class="code">${esc(i.id)}</strong></div><div class="detail-box"><small>Customer</small><strong>${esc(i.email)}</strong></div><div class="detail-box"><small>Plan</small><strong>${esc(i.plan_name)}</strong></div><div class="detail-box"><small>Status</small><strong>${status(i.status)}</strong></div><div class="detail-box"><small>Amount</small><strong>${esc(i.payment_amount_usdt)} USDT</strong></div><div class="detail-box"><small>Base plan price</small><strong>${esc(i.base_price_usdt)} USDT</strong></div><div class="detail-box"><small>Expected payer</small><strong class="code">${esc(i.expected_payer_address||'Not locked')}</strong></div><div class="detail-box"><small>Receiver</small><strong class="code">${esc(i.receiver_address)}</strong></div><div class="detail-box"><small>Created</small><strong>${fmtDate(i.created_at)}</strong></div><div class="detail-box"><small>Expires</small><strong>${fmtDate(i.expires_at)}</strong></div></div><h4>Blockchain events</h4>${eventRows}<h4>Settlement</h4>${settlement}`,'CRYPTO BILLING') }catch(e){showAlert(e.message)}};
$('billing-search-btn').onclick=loadBilling;$('billing-refresh').onclick=loadBilling;$('billing-search').onkeydown=e=>{if(e.key==='Enter')loadBilling()};$('billing-reconcile').onclick=async()=>{try{const d=await req('/v1/admin/billing/reconcile',{method:'POST',body:{}});showAlert(`Reconciliation complete. ${d.billing.expired_invoices} invoices expired.`,true);await loadBilling();await loadOverview()}catch(e){showAlert(e.message)}};
async function loadLegacyPayments(){const d=await req('/v1/admin/payments?limit=100');$('payments-table').innerHTML=d.data.map(p=>`<tr><td><strong>${esc(p.email)}</strong><div class="muted">${esc(p.user_id)}</div></td><td>$${Number(p.amount_usdt).toFixed(2)}</td><td>${esc(p.network||'—')}<div class="code">${esc(p.tx_hash||'')}</div></td><td>${status(p.status)}</td><td>${esc(p.invoice_ref||'—')}</td><td>${fmtDate(p.created_at)}</td></tr>`).join('')||`<tr><td colspan="6" class="muted">No legacy records.</td></tr>`}
$('load-legacy-payments').onclick=loadLegacyPayments;

async function loadCoupons(){const d=await req('/v1/admin/coupons');$('coupons-table').innerHTML=d.coupons.map(c=>`<tr><td><b class="code">${esc(c.code)}</b></td><td>${c.discount_type==='percent'?c.discount_value+'%':'$'+c.discount_value+' USDT'}</td><td>${esc(c.plan_id||'All')}</td><td>${c.used_count}${c.max_redemptions?'/'+c.max_redemptions:''}</td><td>${fmtDate(c.starts_at)} — ${fmtDate(c.ends_at)}</td><td>${status(c.active?'active':'disabled')}</td><td><button class="small-btn" onclick="toggleCoupon('${c.id}',${!c.active})">${c.active?'Disable':'Enable'}</button></td></tr>`).join('')||`<tr><td colspan="7" class="muted">No coupons yet.</td></tr>`}window.toggleCoupon=async(id,active)=>{try{await req(`/v1/admin/coupons/${id}`,{method:'POST',body:{active}});loadCoupons()}catch(e){showAlert(e.message)}};$('new-coupon').onclick=()=>openModal('New coupon',`<div class="modal-form"><label>Code<input id="cup-code" placeholder="WELCOME20"></label><label>Discount type<select id="cup-type"><option value="percent">Percent</option><option value="fixed_usdt">Fixed USDT</option></select></label><label>Value<input id="cup-value" type="number" step="0.01"></label><label>Plan (optional)<select id="cup-plan"><option value="">All plans</option>${state.plans.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>Max redemptions<input id="cup-max" type="number"></label><label>Ends at<input id="cup-end" placeholder="ISO datetime optional"></label><div class="modal-actions"><button class="primary" id="save-cup">Create coupon</button></div></div>`);$('save-cup').onclick=async()=>{try{await req('/v1/admin/coupons',{method:'POST',body:{code:$('cup-code').value,discount_type:$('cup-type').value,discount_value:+$('cup-value').value,plan_id:$('cup-plan').value||null,max_redemptions:$('cup-max').value?+$('cup-max').value:null,ends_at:$('cup-end').value||null}});closeModal();showAlert('Coupon created.',true);loadCoupons()}catch(e){showAlert(e.message)}};
async function loadGrants(){const d=await req('/v1/admin/grants');$('grants-table').innerHTML=d.grants.map(g=>`<tr><td><strong>${esc(g.email)}</strong><div class="muted">${esc(g.user_id)}</div></td><td>${esc(g.plan_id)}</td><td>${esc(g.reason)}</td><td>${fmtDate(g.ends_at)}</td><td>${status(g.status)}</td><td>${g.status==='active'?`<button class="small-btn danger-btn" onclick="revokeGrant('${g.id}')">Revoke</button>`:'—'}</td></tr>`).join('')||`<tr><td colspan="6" class="muted">No grants yet.</td></tr>`}window.revokeGrant=async id=>{try{await req(`/v1/admin/grants/${id}`,{method:'POST',body:{}});showAlert('Grant revoked.',true);loadGrants()}catch(e){showAlert(e.message)}};$('new-grant').onclick=()=>openModal('Grant API access',`<div class="modal-form"><label>User ID<input id="gr-user"></label><label>Plan<select id="gr-plan">${state.plans.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>Reason<textarea id="gr-reason" placeholder="Partner program, launch grant, support case…"></textarea></label><label>Ends at<input id="gr-end" placeholder="ISO datetime optional"></label><div class="modal-actions"><button class="primary" id="save-gr">Create grant</button></div></div>`);$('save-gr').onclick=async()=>{try{await req('/v1/admin/grants',{method:'POST',body:{user_id:$('gr-user').value,plan_id:$('gr-plan').value,reason:$('gr-reason').value,ends_at:$('gr-end').value||null}});closeModal();showAlert('Grant created.',true);loadGrants()}catch(e){showAlert(e.message)}};
async function loadAds(){const d=await req('/v1/admin/ads');$('ads-grid').innerHTML=d.ads.map(a=>`<div class="ad-card"><div class="ad-meta"><span class="tag">${esc(a.placement)}</span><span class="tag">${esc(a.audience)}</span><span class="tag">priority ${a.priority}</span>${status(a.active?'active':'disabled')}</div><h3>${esc(a.title)}</h3><p>${esc(a.body)}</p><div class="muted">${esc(a.cta_label||'')} ${esc(a.cta_url||'')}</div><div class="modal-actions"><button class="small-btn" onclick="toggleAd('${a.id}',${!a.active})">${a.active?'Disable':'Enable'}</button></div></div>`).join('')||'<div class="panel"><p class="muted">No promotions yet.</p></div>'}window.toggleAd=async(id,active)=>{try{await req(`/v1/admin/ads/${id}`,{method:'POST',body:{active}});loadAds()}catch(e){showAlert(e.message)}};$('new-ad').onclick=()=>openModal('New promotion',`<div class="modal-form"><label>Title<input id="ad-title"></label><label>Message<textarea id="ad-body"></textarea></label><label>CTA label<input id="ad-cta"></label><label>CTA URL<input id="ad-url" placeholder="https://..."></label><label>Placement<select id="ad-placement"><option>banner</option><option>homepage</option><option>developer</option><option>results</option></select></label><label>Audience<select id="ad-audience"><option>all</option><option>logged_in</option><option>developer</option><option>pro</option></select></label><label>Priority<input id="ad-prio" type="number" value="0"></label><label>Ends at<input id="ad-end" placeholder="ISO datetime optional"></label><div class="modal-actions"><button class="primary" id="save-ad">Create promotion</button></div></div>`);$('save-ad').onclick=async()=>{try{await req('/v1/admin/ads',{method:'POST',body:{title:$('ad-title').value,body:$('ad-body').value,cta_label:$('ad-cta').value,cta_url:$('ad-url').value,placement:$('ad-placement').value,audience:$('ad-audience').value,priority:+$('ad-prio').value,ends_at:$('ad-end').value||null}});closeModal();showAlert('Promotion created.',true);loadAds()}catch(e){showAlert(e.message)}};
async function loadEmbeds(){const d=await req('/v1/admin/embed/apps');$('embeds-table').innerHTML=d.apps.map(a=>{const used=a.usage?.submitted||0;const quota=a.monthly_quota<0?'∞':a.monthly_quota.toLocaleString();return `<tr><td><strong>${esc(a.name)}</strong><div class="muted code">${esc(a.public_key)}</div></td><td>${a.allowed_origins.slice(0,2).map(esc).join('<br>')}${a.allowed_origins.length>2?`<br><span class="muted">+${a.allowed_origins.length-2} more</span>`:''}</td><td>${used.toLocaleString()} / ${quota}<div class="muted">${(a.usage?.completed||0).toLocaleString()} completed · ${(a.usage?.failed||0).toLocaleString()} failed</div></td><td>${a.rate_limit_per_minute}/min</td><td>${status(a.active?'active':'disabled')}</td><td>${fmtDate(a.created_at)}</td><td><div class="row-actions"><button class="small-btn" onclick="editEmbed('${a.id}')">Edit</button><button class="small-btn" onclick="viewEmbedAnalytics('${a.id}')">Analytics</button><button class="small-btn" onclick="rotateEmbed('${a.id}')">Rotate</button><button class="small-btn" onclick="toggleEmbed('${a.id}',${!a.active})">${a.active?'Disable':'Enable'}</button></div></td></tr>`}).join('')||`<tr><td colspan="7" class="muted">No Embed applications yet.</td></tr>`}
async function editEmbed(id){const d=(await req('/v1/admin/embed/apps')).apps.find(x=>x.id===id);if(!d)return;openModal('Edit Embed application',`<div class="modal-form"><label>Name<input id="e-name" value="${esc(d.name)}"></label><label>Allowed origins<textarea id="e-origins">${esc(d.allowed_origins.join('\n'))}</textarea></label><label>Monthly quota (-1 = unlimited)<input id="e-quota" type="number" value="${d.monthly_quota}"></label><label>Rate limit / minute<input id="e-rate" type="number" value="${d.rate_limit_per_minute}"></label><label>Status<select id="e-active"><option value="true">Active</option><option value="false">Disabled</option></select></label><div class="muted code">Public key: ${esc(d.public_key)}</div><div class="modal-actions"><button class="primary" id="save-embed">Save</button></div></div>`);$('e-active').value=String(d.active);$('save-embed').onclick=async()=>{try{await req(`/v1/admin/embed/apps/${id}`,{method:'POST',body:{name:$('e-name').value,allowed_origins:$('e-origins').value.split('\n').map(x=>x.trim()).filter(Boolean),monthly_quota:+$('e-quota').value,rate_limit_per_minute:+$('e-rate').value,active:$('e-active').value==='true'}});closeModal();showAlert('Embed application updated.',true);loadEmbeds()}catch(e){showAlert(e.message)}}}
$('new-embed').onclick=()=>openModal('New Embed application',`<div class="modal-form"><label>Name<input id="e-name" placeholder="CoinExample Widget"></label><label>Allowed origins<textarea id="e-origins" placeholder="https://example.com\nhttps://www.example.com"></textarea></label><label>Monthly quota<input id="e-quota" type="number" value="1000"></label><label>Rate limit / minute<input id="e-rate" type="number" value="30"></label><div class="modal-actions"><button class="primary" id="save-embed">Create application</button></div></div>`);$('save-embed').onclick=async()=>{try{const d=await req('/v1/admin/embed/apps',{method:'POST',body:{name:$('e-name').value,allowed_origins:$('e-origins').value.split('\n').map(x=>x.trim()).filter(Boolean),monthly_quota:+$('e-quota').value,rate_limit_per_minute:+$('e-rate').value,active:true}});const key=d.app.public_key;const snippet=`<div data-smartrisk-widget data-app="${key}" data-theme="dark"></div>\n<script src="${location.origin}/assets/embed.js" defer></script>`;openModal('Embed application created',`<div class="modal-form"><label>Public key<input id="new-embed-key" value="${esc(key)}" readonly></label><label>Embed code<textarea id="new-embed-code">${esc(snippet)}</textarea></label><p class="muted">The public key is a browser-visible integration identifier, not a secret. Allowed origins are enforced by the widget bootstrap and CSP.</p><div class="modal-actions"><button class="primary" id="copy-embed-code">Copy embed code</button></div></div>`);$('copy-embed-code').onclick=async()=>{try{await navigator.clipboard.writeText(snippet);showAlert('Embed code copied.',true)}catch{showAlert('Copy failed; select the code and copy it manually.')}};loadEmbeds()}catch(e){showAlert(e.message)}}
window.toggleEmbed=async(id,active)=>{try{await req(`/v1/admin/embed/apps/${id}/toggle`,{method:'POST',body:{active}});showAlert('Embed status updated.',true);loadEmbeds()}catch(e){showAlert(e.message)}};
window.rotateEmbed=async id=>{if(!confirm('Rotate this public key? Existing integrations using the current key will stop working.'))return;try{const d=await req(`/v1/admin/embed/apps/${id}/rotate`,{method:'POST',body:{}});showAlert(`New public key: ${d.app.public_key}`,true);editEmbed(id)}catch(e){showAlert(e.message)}};
window.viewEmbedAnalytics=async id=>{try{const d=await req(`/v1/admin/embed/apps/${id}/analytics?days=30`);const days=d.daily.map(x=>`<tr><td>${esc(x.date)}</td><td>${x.submitted}</td><td>${x.completed}</td><td>${x.failed}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">No events in this period.</td></tr>';const origins=d.origins.map(x=>`<div class="mini-plan"><b>${esc(x.origin)}</b><span class="muted">${x.submitted} submitted</span></div>`).join('')||'<p class="muted">No origins recorded.</p>';openModal('Embed analytics',`<div class="detail-grid"><div class="detail-box"><small>Period</small><strong>${d.period_days} days</strong></div><div class="detail-box"><small>Tracked origins</small><strong>${d.origins.length}</strong></div></div><h4>Daily usage</h4><div class="panel table-panel"><table><thead><tr><th>Date</th><th>Submitted</th><th>Completed</th><th>Failed</th></tr></thead><tbody>${days}</tbody></table></div><h4>Origins</h4>${origins}`)}catch(e){showAlert(e.message)}};
async function loadSettings(){const d=await req('/v1/admin/settings');state.settings=d.settings;$('settings-list').innerHTML=d.settings.map(s=>`<div class="setting-card"><div><strong>${esc(s.key)}</strong><small>${esc(s.description||'')}</small></div><button class="toggle ${s.value==='true'?'on':''}" data-setting="${esc(s.key)}" data-value="${esc(s.value)}"></button></div>`).join('');document.querySelectorAll('#settings-list .toggle').forEach(b=>b.onclick=()=>toggleSetting(b.dataset.setting,b.dataset.value!=='true'))}
async function loadAudit(){const d=await req('/v1/admin/audit?limit=100');$('audit-table').innerHTML=d.data.map(a=>`<tr><td>${fmtDate(a.created_at)}</td><td>${esc(a.admin_email||'—')}</td><td>${esc(a.action)}</td><td>${esc(a.target_type||'')} ${esc(a.target_id||'')}</td><td><code class="code">${esc(JSON.stringify(a.details))}</code></td></tr>`).join('')||`<tr><td colspan="5" class="muted">No audit events yet.</td></tr>`}
$('refresh').onclick=()=>{const active=document.querySelector('.section.active')?.id.replace('section-','')||'overview';activateSection(active)};$('logout').onclick=async()=>{await req('/v1/auth/logout',{method:'POST'});location.href='/auth?mode=login'};
bootstrap();
